# Adjust our load path for testing
lib = File.expand_path('../../../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require 'dest/rake'

Dest::Project::Base.setup do |proj|
  proj.frameworks << 'Cocoa'
  proj.add_source 'main.m'
  proj.add_source_directory 'Example'
end
Dest::Rake.setup
